FROM microsoft/dotnet:2.2-runtime
RUN apt-get update && apt-get install nano -y && apt-get install vim -y
RUN cp /usr/share/zoneinfo/Europe/Prague /etc/localtime
WORKDIR /publish
COPY /publish /publish
ENTRYPOINT dotnet zapsi_service_optimont_importer.dll
